#!/bin/bash
# ----------------------------------------------------
# That autogenerated script for compiling your library
# ----------------------------------------------------

mkdir .build 2>/dev/null
cd .build
cmake ../
cmake --build . -j 16
cd ..
cp .build/*.so .
